repos:
  - repo: local
    hooks:
      - id: run-ruff
        name: Run ruff formatter before commit
        entry: poetry -C ApiClientes/pyproject.toml run python -m ruff format .
        language: system
        always_run: true
        pass_filenames: false

  - repo: local
    hooks:
      - id: run-ruff-checks
        name: Run ruff checks before commit
        entry: poetry -C ApiClientes/pyproject.toml run python -m ruff check .
        language: system
        always_run: true
        pass_filenames: false
  
  - repo: local
    hooks:
      - id: run-pytest
        name: Run pytest before commit
        entry: sh -c 'cd ApiClientes && poetry run python -m pytest'
        language: system
        always_run: true
        pass_filenames: false
