---
services:
  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6380:6379"
    #volumes:
      #- /data
    deploy: &limit50
      resources:
        limits:
          memory: 50M

  api:
    depends_on: 
    - redis
    build: .
    image: localhost/case
    container_name: case-api
    ports:
    - "127.0.0.1:8081:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 30s
