---
services:
  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6380:6379"
    #volumes:
      #- /data
    deploy: &limit50
      resources:
        limits:
          memory: 50M

  api:
    depends_on: 
    - redis
    - caddy
    build: 
      context: .
      target: runtime
    image: localhost/case
    container_name: case-api
    expose:
    - 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 30s
  caddy:
    build: 
      context: .
      target: caddy-runtime
    image: localhost/case-caddy
    container_name: case-caddy
    volumes:
    - ./Caddy/Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data
    - caddy_config:/config
    ports:
    - "127.0.0.1:8080:8080"
volumes:
  caddy_data:
  caddy_config:
