---
services:
  redis:
    image: redis:alpine
    expose:
      - 6379
    volumes:
      - ./redis_data:/data
    deploy: &limit50
      resources:
        limits:
          memory: 50M

  api:
    depends_on: 
    - redis
    build: .
    image: localhost/case
    container_name: case-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 30s
